package compose

import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.TypeSpec
import org.yaml.snakeyaml.Yaml
import java.io.File

private val composableAnnotation = ClassName("androidx.compose.runtime", "Composable")

@Suppress("UNCHECKED_CAST")
fun main(args: Array<String>) {
    if (args.size < 2) {
        println("Usage: <dslYamlPath> <outputDir>")
        return
    }

    val dslPath = File(args[0])
    val outputDir = File(args[1])
    val payload = Yaml().load<Map<String, Any>>(dslPath.readText())
    val screens = payload["screens"] as? List<Map<String, Any>> ?: emptyList()

    outputDir.mkdirs()
    screens.forEach { screen ->
        val rawName = screen["name"]?.toString().orEmpty()
        val screenName = pascal(rawName.ifBlank { "Unknown" }) + "Screen"
        val file = buildScreenFile(screenName)
        file.writeTo(outputDir)
    }
}

private fun buildScreenFile(screenName: String): FileSpec {
    val composable = FunSpec.builder(screenName)
        .addAnnotation(composableAnnotation)
        .addStatement("// DO NOT EDIT: generated by KotlinPoet")
        .addComment("TODO(codegen): wire DSL node rendering")
        .build()

    val preview = FunSpec.builder(screenName.replace("Screen", "Preview"))
        .addAnnotation(composableAnnotation)
        .addAnnotation(
            AnnotationSpec.builder(ClassName("androidx.compose.ui.tooling.preview", "Preview"))
                .build()
        )
        .addStatement("%L()", screenName)
        .build()

    return FileSpec.builder("com.example.generated.screens", screenName)
        .addFunction(composable)
        .addFunction(preview)
        .build()
}

private fun pascal(value: String): String {
    val chunks = value.replace("_", " ").split(" ").filter { it.isNotBlank() }
    if (chunks.isEmpty()) return "Unknown"
    return chunks.joinToString("") { it.replaceFirstChar(Char::uppercaseChar) }
}
