package compose

import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import org.yaml.snakeyaml.Yaml
import java.io.File

private val composableAnnotation = ClassName("androidx.compose.runtime", "Composable")

@Suppress("UNCHECKED_CAST")
fun main(args: Array<String>) {
    if (args.size !in 2..3) {
        println("Usage: <dslYamlPath> <outputDir> [packageBase]")
        return
    }
    val packageBase = if (args.size >= 3) args[2] else "com.example.generated"
    runDslToComposeCodegen(
        dslPath = File(args[0]),
        outputDir = File(args[1]),
        packageBase = packageBase,
    )
}

@Suppress("UNCHECKED_CAST")
fun runDslToComposeCodegen(dslPath: File, outputDir: File, packageBase: String) {
    require(dslPath.exists()) { "DSL file does not exist: ${dslPath.absolutePath}" }

    val payload = Yaml().load<Map<String, Any>>(dslPath.readText())
    val screens = payload["screens"] as? List<Map<String, Any>> ?: emptyList()

    outputDir.mkdirs()
    screens.forEach { screen ->
        val rawName = screen["name"]?.toString().orEmpty()
        val screenName = pascal(rawName.ifBlank { "Unknown" }) + "Screen"
        val file = buildScreenFile(screenName = screenName, packageBase = packageBase, screenNode = screen)
        file.writeTo(outputDir)
    }
}

private fun buildScreenFile(screenName: String, packageBase: String, screenNode: Map<String, Any>): FileSpec {
    val body = emitNode(node = screenNode)

    val composable = FunSpec.builder(screenName)
        .addAnnotation(composableAnnotation)
        .addComment("DO NOT EDIT: generated by KotlinPoet")
        .addCode(body)
        .build()

    val preview = FunSpec.builder(screenName.replace("Screen", "Preview"))
        .addAnnotation(composableAnnotation)
        .addAnnotation(
            AnnotationSpec.builder(ClassName("androidx.compose.ui.tooling.preview", "Preview"))
                .build()
        )
        .addStatement("%L()", screenName)
        .build()

    return FileSpec.builder("$packageBase.screens", screenName)
        .addImport("androidx.compose.foundation.lazy", "LazyColumn")
        .addImport("androidx.compose.foundation.lazy", "LazyRow")
        .addImport("androidx.compose.foundation.layout", "Arrangement")
        .addImport("androidx.compose.foundation.layout", "Box")
        .addImport("androidx.compose.foundation.layout", "Column")
        .addImport("androidx.compose.foundation.layout", "Row")
        .addImport("androidx.compose.foundation.layout", "height")
        .addImport("androidx.compose.foundation.layout", "padding")
        .addImport("androidx.compose.foundation.layout", "width")
        .addImport("androidx.compose.material3", "AlertDialog")
        .addImport("androidx.compose.material3", "Checkbox")
        .addImport("androidx.compose.material3", "ModalBottomSheet")
        .addImport("androidx.compose.material3", "Text")
        .addImport("androidx.compose.ui", "Modifier")
        .addImport("androidx.compose.ui.unit", "dp")
        .addFunction(composable)
        .addFunction(preview)
        .build()
}

private fun pascal(value: String): String {
    val chunks = value.replace("_", " ").split(" ").filter { it.isNotBlank() }
    if (chunks.isEmpty()) return "Unknown"
    return chunks.joinToString("") { it.replaceFirstChar(Char::uppercaseChar) }
}

@Suppress("UNCHECKED_CAST")
private fun emitNode(node: Map<String, Any>): CodeBlock {
    val nodeKey = node["node"]?.toString().orEmpty()
    val props = node["props"] as? Map<String, Any> ?: emptyMap()
    val children = (node["children"] as? List<Map<String, Any>> ?: emptyList())
    val modifier = buildModifier(props)

    return when (nodeKey) {
        "screen/page", "layout/column" -> {
            val spacing = props["spacingDp"]?.toString() ?: "0"
            CodeBlock.builder()
                .beginControlFlow(
                    "Column(modifier = %L, verticalArrangement = Arrangement.spacedBy(%L.dp))",
                    modifier,
                    spacing,
                )
                .apply {
                    children.forEach { child -> add(emitNode(child)) }
                }
                .endControlFlow()
                .build()
        }
        "layout/row" -> {
            val spacing = props["spacingDp"]?.toString() ?: "0"
            CodeBlock.builder()
                .beginControlFlow(
                    "Row(modifier = %L, horizontalArrangement = Arrangement.spacedBy(%L.dp))",
                    modifier,
                    spacing,
                )
                .apply {
                    children.forEach { child -> add(emitNode(child)) }
                }
                .endControlFlow()
                .build()
        }
        "layout/box" -> {
            CodeBlock.builder()
                .beginControlFlow("Box(modifier = %L)", modifier)
                .apply {
                    children.forEach { child -> add(emitNode(child)) }
                }
                .endControlFlow()
                .build()
        }
        "content/text" -> {
            val text = (props["text"]?.toString() ?: node["name"]?.toString().orEmpty())
            CodeBlock.builder()
                .addStatement("Text(text = %S, modifier = %L)", text, modifier)
                .build()
        }
        "component/checkbox" -> {
            val checked = (node["state"]?.toString() == "checked")
            CodeBlock.builder()
                .addStatement("Checkbox(checked = %L, onCheckedChange = {}, modifier = %L)", checked, modifier)
                .build()
        }
        "component/listVertical" -> {
            CodeBlock.builder()
                .beginControlFlow("LazyColumn(modifier = %L)", modifier)
                .apply {
                    children.forEach { child ->
                        beginControlFlow("item")
                        add(emitNode(child))
                        endControlFlow()
                    }
                }
                .endControlFlow()
                .build()
        }
        "component/listHorizontal" -> {
            CodeBlock.builder()
                .beginControlFlow("LazyRow(modifier = %L)", modifier)
                .apply {
                    children.forEach { child ->
                        beginControlFlow("item")
                        add(emitNode(child))
                        endControlFlow()
                    }
                }
                .endControlFlow()
                .build()
        }
        "screen/bottomSheet" -> {
            CodeBlock.builder()
                .beginControlFlow("ModalBottomSheet(onDismissRequest = {})")
                .apply {
                    children.forEach { child -> add(emitNode(child)) }
                }
                .endControlFlow()
                .build()
        }
        "screen/dialog" -> {
            CodeBlock.builder()
                .add("AlertDialog(\n")
                .indent()
                .add("onDismissRequest = {},\n")
                .add("confirmButton = { Text(%S) },\n", "OK")
                .add("text = {\n")
                .indent()
                .apply {
                    children.forEach { child -> add(emitNode(child)) }
                }
                .unindent()
                .add("}\n")
                .unindent()
                .add(")\n")
                .build()
        }
        else -> {
            CodeBlock.builder()
                .beginControlFlow("Box(modifier = %L)", modifier)
                .add("// TODO(codegen): unsupported node %S\n", nodeKey)
                .apply {
                    children.forEach { child -> add(emitNode(child)) }
                }
                .endControlFlow()
                .build()
        }
    }
}

private fun buildModifier(props: Map<String, Any>): String {
    val chain = mutableListOf("Modifier")
    val width = props["widthDp"]?.toString()
    val height = props["heightDp"]?.toString()
    if (width != null && height != null) {
        chain += ".width(${width}.dp).height(${height}.dp)"
    } else if (width != null) {
        chain += ".width(${width}.dp)"
    } else if (height != null) {
        chain += ".height(${height}.dp)"
    }
    val padding = props["padding"] as? Map<*, *>
    if (padding != null) {
        val l = padding["leftDp"]?.toString() ?: "0"
        val t = padding["topDp"]?.toString() ?: "0"
        val r = padding["rightDp"]?.toString() ?: "0"
        val b = padding["bottomDp"]?.toString() ?: "0"
        chain += ".padding(start=${l}.dp, top=${t}.dp, end=${r}.dp, bottom=${b}.dp)"
    }
    return chain.joinToString("")
}
