from __future__ import annotations

import logging
from pathlib import Path
from typing import Any


MODIFIER_ORDER = [
    "fill",
    "size",
    "padding",
    "offset",
    "decoration",
    "align",
    "semantics",
]


class ComposeGenerator:
    def __init__(self, output_root: Path, package_name: str = "com.example.generated") -> None:
        self.output_root = output_root
        self.package_name = package_name
        self.screens_dir = output_root / "screens"
        self.components_dir = output_root / "components"
        self.previews_dir = output_root / "previews"
        self.logger = logging.getLogger("pipeline.compose")
        self.screens_dir.mkdir(parents=True, exist_ok=True)
        self.components_dir.mkdir(parents=True, exist_ok=True)
        self.previews_dir.mkdir(parents=True, exist_ok=True)

    def generate(self, dsl: dict[str, Any]) -> list[Path]:
        generated: list[Path] = []
        screens = dsl.get("screens", [])
        self.logger.info("Compose generation started: screens=%s", len(screens))
        for screen in dsl["screens"]:
            screen_name = _pascal(screen["name"])
            screen_path = self.screens_dir / f"{screen_name}Screen.kt"
            preview_path = self.previews_dir / f"{screen_name}Preview.kt"
            screen_path.write_text(self._build_screen_file(screen_name, screen), encoding="utf-8")
            preview_path.write_text(self._build_preview_file(screen_name), encoding="utf-8")
            generated.extend([screen_path, preview_path])
            self.logger.info("Generated screen pair: %s", screen_name)
        self.logger.info("Compose generation finished: files=%s", len(generated))
        return generated

    def _build_screen_file(self, screen_name: str, screen_node: dict[str, Any]) -> str:
        body = self._emit_node(screen_node, 1)
        return f"""@file:Suppress("UnusedImport", "FunctionName")
package {self.package_name}.screens

import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.offset
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.grid.GridCells
import androidx.compose.foundation.lazy.grid.LazyVerticalGrid
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.Checkbox
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.DatePicker
import androidx.compose.material3.DatePickerDialog
import androidx.compose.material3.Divider
import androidx.compose.material3.Icon
import androidx.compose.material3.LinearProgressIndicator
import androidx.compose.material3.ModalBottomSheet
import androidx.compose.material3.RadioButton
import androidx.compose.material3.Slider
import androidx.compose.material3.Surface
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.material3.TextField
import androidx.compose.material3.TimePicker
import androidx.compose.material3.TimePickerDialog
import androidx.compose.runtime.Composable
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import com.example.R

// DO NOT EDIT: generated by pipeline
@Composable
fun {screen_name}Screen() {{
{body}
}}
"""

    def _emit_node(self, node: dict[str, Any], indent: int) -> str:
        space = "    " * indent
        node_key = node["node"]
        props = node.get("props", {})
        children = node.get("children", [])
        child_code = "\n".join(self._emit_node(x, indent + 1) for x in children)
        modifier = self._build_modifier(props)
        text = _escape(str(props.get("text") or node["name"]))
        spacing = props.get("spacingDp", 0)
        layout = str(props.get("layout", "box"))
        res_name = _safe_res_name(str(props.get("resourceName") or node["name"] or "placeholder"))
        checked = str(node.get("state") == "checked").lower()

        if node_key == "screen/page":
            return f"""{space}LazyColumn(
{space}    modifier = {modifier},
{space}    verticalArrangement = Arrangement.spacedBy({spacing}.dp)
{space}) {{
{space}    item {{
{space}        Column(verticalArrangement = Arrangement.spacedBy({spacing}.dp)) {{
{child_code}
{space}        }}
{space}    }}
{space}}}"""
        if node_key == "screen/bottomSheet":
            return f"""{space}ModalBottomSheet(onDismissRequest = {{}}) {{
{space}    Column(
{space}        modifier = {modifier}.padding(16.dp),
{space}        verticalArrangement = Arrangement.spacedBy({spacing}.dp)
{space}    ) {{
{child_code}
{space}    }}
{space}}}"""
        if node_key == "screen/dialog":
            return f"""{space}AlertDialog(
{space}    onDismissRequest = {{}},
{space}    confirmButton = {{ Button(onClick = {{}}) {{ Text("OK") }} }},
{space}    text = {{
{space}        Column(
{space}            modifier = {modifier},
{space}            verticalArrangement = Arrangement.spacedBy({spacing}.dp)
{space}        ) {{
{child_code}
{space}        }}
{space}    }}
{space})"""
        if node_key in {"layout/column", "layout/stack"} or (
            node_key in {"layout/constraint", "layout/flow"} and layout == "column"
        ):
            return f"""{space}Column(
{space}    modifier = {modifier},
{space}    verticalArrangement = Arrangement.spacedBy({spacing}.dp)
{space}) {{
{child_code}
{space}}}"""
        if node_key == "layout/row" or (node_key in {"layout/constraint", "layout/flow"} and layout == "row"):
            return f"""{space}Row(
{space}    modifier = {modifier},
{space}    horizontalArrangement = Arrangement.spacedBy({spacing}.dp)
{space}) {{
{child_code}
{space}}}"""
        if node_key == "layout/grid" or layout == "grid":
            return f"""{space}LazyVerticalGrid(
{space}    columns = GridCells.Fixed(2),
{space}    modifier = {modifier}
{space}) {{
{space}    item {{
{space}        Column(verticalArrangement = Arrangement.spacedBy({spacing}.dp)) {{
{child_code}
{space}        }}
{space}    }}
{space}}}"""
        if node_key in {"layout/box", "layout/constraint", "layout/flow"}:
            return f"""{space}Box(modifier = {modifier}) {{
{child_code}
{space}}}"""
        if node_key == "content/text":
            return f"""{space}Text(
{space}    text = "{text}",
{space}    modifier = {modifier}
{space})"""
        if node_key in {"content/icon", "content/image", "content/illustration"}:
            return f"""{space}Image(
{space}    painter = painterResource(id = R.drawable.{res_name}),
{space}    contentDescription = "{_escape(node.get("name", ""))}",
{space}    modifier = {modifier}
{space})"""
        if node_key in {"content/video", "content/lottie"}:
            return f"""{space}Surface(
{space}    modifier = {modifier},
{space}    shape = RoundedCornerShape(8.dp),
{space}    color = Color(0xFFE0E0E0)
{space}) {{
{space}    Text(text = "Media: {text}", modifier = Modifier.padding(8.dp))
{space}}}"""
        if node_key in {"component/button", "component/fab", "component/iconButton", "component/chip", "component/toggleChip", "component/segmentedControl"}:
            return f"""{space}Button(
{space}    onClick = {{}},
{space}    modifier = {modifier}
{space}) {{
{space}    Text("{text}")
{space}}}"""
        if node_key in {"component/textField", "component/searchField"}:
            return f"""{space}TextField(
{space}    value = "",
{space}    onValueChange = {{}},
{space}    label = {{ Text("{text}") }},
{space}    modifier = {modifier}
{space})"""
        if node_key == "component/passwordField":
            return f"""{space}BasicTextField(
{space}    value = "",
{space}    onValueChange = {{}},
{space}    modifier = {modifier}
{space})"""
        if node_key == "component/checkbox":
            return f"""{space}Checkbox(
{space}    checked = {checked},
{space}    onCheckedChange = {{}},
{space}    modifier = {modifier}
{space})"""
        if node_key in {"component/switch", "component/radio"}:
            control = "Switch" if node_key == "component/switch" else "RadioButton"
            return f"""{space}{control}(
{space}    checked = {checked},
{space}    onClick = {{}},
{space}    modifier = {modifier}
{space})"""
        if node_key in {"component/slider", "component/rangeSlider"}:
            return f"""{space}Slider(
{space}    value = 0.5f,
{space}    onValueChange = {{}},
{space}    modifier = {modifier}
{space})"""
        if node_key == "component/stepper":
            return f"""{space}Row(modifier = {modifier}, horizontalArrangement = Arrangement.spacedBy(8.dp)) {{
{space}    Button(onClick = {{}}) {{ Text("-") }}
{space}    Text("0")
{space}    Button(onClick = {{}}) {{ Text("+") }}
{space}}}"""
        if node_key == "component/datePicker":
            return f"""{space}Text(
{space}    text = "DatePicker: {text}",
{space}    modifier = {modifier}
{space})"""
        if node_key == "component/timePicker":
            return f"""{space}Text(
{space}    text = "TimePicker: {text}",
{space}    modifier = {modifier}
{space})"""
        if node_key == "component/dropdown":
            return f"""{space}TextField(
{space}    value = "Option 1",
{space}    onValueChange = {{}},
{space}    label = {{ Text("{text}") }},
{space}    modifier = {modifier}
{space})"""
        if node_key == "component/list":
            return f"""{space}LazyColumn(
{space}    modifier = {modifier},
{space}    verticalArrangement = Arrangement.spacedBy({spacing}.dp)
{space}) {{
{space}    item {{
{space}        Column(verticalArrangement = Arrangement.spacedBy({spacing}.dp)) {{
{child_code}
{space}        }}
{space}    }}
{space}}}"""
        if node_key in {"component/listItem", "component/card"}:
            return f"""{space}Surface(
{space}    modifier = {modifier},
{space}    shape = RoundedCornerShape(10.dp),
{space}    color = Color(0xFFF3F3F3)
{space}) {{
{space}    Column(
{space}        modifier = Modifier.padding(12.dp),
{space}        verticalArrangement = Arrangement.spacedBy({spacing}.dp)
{space}    ) {{
{child_code}
{space}    }}
{space}}}"""
        if node_key == "component/table":
            return f"""{space}Surface(
{space}    modifier = {modifier}.border(1.dp, Color(0x33000000), RoundedCornerShape(8.dp)),
{space}    shape = RoundedCornerShape(8.dp)
{space}) {{
{space}    Column(verticalArrangement = Arrangement.spacedBy({spacing}.dp)) {{
{child_code}
{space}    }}
{space}}}"""
        if node_key == "component/badge":
            return f"""{space}Surface(
{space}    modifier = {modifier},
{space}    shape = RoundedCornerShape(999.dp),
{space}    color = Color(0xFFE0E0E0)
{space}) {{
{space}    Text(text = "{text}", modifier = Modifier.padding(horizontal = 8.dp, vertical = 4.dp))
{space}}}"""
        if node_key == "component/avatar":
            return f"""{space}Surface(
{space}    modifier = {modifier}.size(40.dp),
{space}    shape = CircleShape,
{space}    color = Color(0xFFD0D0D0)
{space}) {{
{space}    Box(modifier = Modifier.fillMaxSize()) {{
{space}        Text(text = "{text[:2]}")
{space}    }}
{space}}}"""
        if node_key == "component/progressLinear":
            return f"""{space}LinearProgressIndicator(
{space}    progress = {{ 0.5f }},
{space}    modifier = {modifier}
{space})"""
        if node_key in {"component/progressCircular", "feedback/loading"}:
            return f"""{space}CircularProgressIndicator(modifier = {modifier})"""
        if node_key == "component/divider":
            return f"""{space}Divider(modifier = {modifier})"""
        if node_key in {"component/snackbar", "component/toast", "component/tooltip", "component/banner", "feedback/error", "feedback/empty", "feedback/success", "feedback/offline"}:
            return f"""{space}Surface(
{space}    modifier = {modifier},
{space}    shape = RoundedCornerShape(8.dp),
{space}    color = Color(0x26000000)
{space}) {{
{space}    Text(text = "{text}", modifier = Modifier.padding(10.dp))
{space}}}"""
        if node_key == "raw/frame":
            return f"""{space}Box(modifier = {modifier}) {{
{child_code}
{space}}}"""
        # Safe fallback for unsupported DSL nodes.
        return f"""{space}Column(
{space}    modifier = {modifier},
{space}    verticalArrangement = Arrangement.spacedBy({spacing}.dp)
{space}) {{
{space}    Text("Unsupported node: {node_key}")
{child_code}
{space}}}"""

    def _build_modifier(self, props: dict[str, Any]) -> str:
        chain: list[str] = ["Modifier"]
        width = props.get("widthDp")
        height = props.get("heightDp")
        if width and height:
            chain.append(f".width({width}.dp).height({height}.dp)")
        elif width:
            chain.append(f".width({width}.dp)")
        elif height:
            chain.append(f".height({height}.dp)")
        padding = props.get("padding") or {}
        if any(k in padding for k in ("leftDp", "rightDp", "topDp", "bottomDp")):
            chain.append(
                ".padding(start={left}.dp, top={top}.dp, end={right}.dp, bottom={bottom}.dp)".format(
                    left=padding.get("leftDp", 0),
                    top=padding.get("topDp", 0),
                    right=padding.get("rightDp", 0),
                    bottom=padding.get("bottomDp", 0),
                )
            )
        token_ref = props.get("tokenRef")
        if token_ref and isinstance(token_ref, str) and token_ref.startswith("#"):
            chain.append(f".background(Color(0xFF{token_ref[1:]}))")
        x_dp = props.get("xDp")
        y_dp = props.get("yDp")
        if x_dp or y_dp:
            chain.append(f".offset(x={x_dp or 0}.dp, y={y_dp or 0}.dp)")
        content_description = props.get("contentDescription")
        if content_description:
            chain.append(f'.semantics {{ this.contentDescription = "{_escape(str(content_description))}" }}')
        test_tag = props.get("testTag")
        if test_tag:
            chain.append(f'.then(Modifier) // testTag: "{_escape(test_tag)}"')
        return "".join(chain)

    def _build_preview_file(self, screen_name: str) -> str:
        return f"""package {self.package_name}.previews

import androidx.compose.runtime.Composable
import androidx.compose.ui.tooling.preview.Preview
import {self.package_name}.screens.{screen_name}Screen

// DO NOT EDIT: generated by pipeline
@Preview(showBackground = true)
@Composable
fun {screen_name}Preview() {{
    {screen_name}Screen()
}}
"""


def _pascal(value: str) -> str:
    chunks = [x for x in value.replace("_", " ").split() if x]
    if not chunks:
        return "Unknown"
    return "".join(ch[:1].upper() + ch[1:] for ch in chunks)


def _escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace("\"", "\\\"")


def _safe_res_name(value: str) -> str:
    out = []
    for ch in value:
        if ch.isalnum() or ch == "_":
            out.append(ch.lower())
        else:
            out.append("_")
    normalized = "".join(out).strip("_")
    if not normalized:
        return "placeholder"
    if normalized[0].isdigit():
        return f"res_{normalized}"
    return normalized
